apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
   replicas: 1
   selector:
     matchLabels:
       app: demo
   template:
     metadata:
       name: demo
       labels:
         app: demo
     spec:
       containers:
       - image: docker.io/nlapin/neoflex_demo:latest
         name: main
         ports:
           - containerPort: 8080
