apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
   replicas: {{ .Values.replicaCount }}
   selector:
     matchLabels:
       app: {{ .Release.Name }}
   template:
     metadata:
       name: {{ .Release.Name }}
       labels:
         app: {{ .Release.Name }}
     spec:
       containers:
       - image: {{ .Values.container.image }}
         name: {{ .Release.Name }}
         ports:
           - containerPort: {{ .Values.service.port }}
